---
- name: Getting user home dire before become
  local_action: command echo ~
  register: user_home
  become: no

- name: Download WordPress
  get_url:
    url={{ wp_download }}
    dest={{ user_home.stdout }}/latest.tar.gz
    validate_certs=no
  become: no

- name: Extract WordPress
  unarchive:
    src={{ user_home.stdout }}/latest.tar.gz dest={{ user_home.stdout }} copy=no
  become: no

- name: Install php extensions
  apt: name={{ item }} state=present
  with_items:
    - php5-gd 
    - libssh2-php
