---
- name: Adding ServerName and folder permissions to apache conf
  blockinfile:
    dest: /etc/apache2/sites-available/000-default.conf
    block: "{{'\t'}}ServerName {{ ansible_default_ipv4.address }}{{'\n\t'}}<Directory {{ web_root }}>{{'\n\t\t'}}AllowOverride All{{'\n\t'}}</Directory>"
    insertafter: 'DocumentRoot /var/www/html'
    state: present

- name: creating htaccess files
  file: path={{ web_root }}/.htaccess state=touch owner={{ user }} group={{ web_group }} mode=0644

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache
