---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install required software
  apt: name={{ item }} state=present
  ignore_errors: yes
  with_items:
    - apache2
    - mysql-server
    - php5-mysql
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - python-mysqldb

- name: Update default Apache site
  lineinfile:
    dest=/etc/apache2/mods-enabled/dir.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {'regexp': "DirectoryIndex", line: "DirectoryIndex index.php index.html index.cgi  index.pl index.xhtml index.htm"}
  notify:
  - restart apache
